AWSTemplateFormatVersion: 2010-09-09
Description: Lambda IaC with API Test

Parameters:
  LambdaFunctionName:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$
    Default: IaCLambdaAPITest

  S3Bucket:
    Type: String
    Default: mycode-cloudformation

  S3Key:
    Type: String
    Default: Select.zip

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Runtime: python3.8
      Description: RDS DB Select
      FunctionName: !Ref LambdaFunctionName
      Handler: DBSelect.lambda_handler
      Role: !GetAtt IACLambdaRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - sg-06f19d0fbd76eb5ca
        SubnetIds:
          - subnet-00d82a9f06aa159ab
          - subnet-04a49d2ef162cca08

  IACLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IACLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com

      Path: "/"
  lambdaIaCPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: lambdaIaCPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
            Resource: "*"
      Roles:
        - Ref: IACLambdaRole