AWSTemplateFormatVersion: "2010-09-09"
Resources:









  IACLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "IACLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"

      Path: "/"
  lambdaIacTestPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "lambdaIacTestPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "ec2:CreateNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DeleteNetworkInterface"
            Resource: '*'
      Roles:
        - Ref: "IACLambdaRole"