AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ENV:
    Type: String
    Description: Envrionement used by the Cluster / container
    Default: 'DEV'
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC that allows instances access to the Internet.
    Default: 'vpc-0f2516a17f1b3cafb'
  SubnetId1:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at two subnets in your selected VPC
    Default: 'subnet-0139340dd01e4119d'

Resources:
  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ECS-SG
      GroupDescription: ECS Security Group
      VpcId: !Ref 'VpcId'

  EcsSecurityGroupHTTPinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'EcsSecurityGroup'
      IpProtocol: tcp
      FromPort: '8080'
      ToPort: '8080'
      CidrIp: 0.0.0.0/0
  EcsSecurityGroupSSHinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'EcsSecurityGroup'
      IpProtocol: tcp
      FromPort: '22'
      ToPort: '22'
      CidrIp: 0.0.0.0/0
  EcsSecurityGroupALBports:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'EcsSecurityGroup'
      IpProtocol: tcp
      FromPort: '31000'
      ToPort: '61000'
      SourceSecurityGroupId: !Ref 'EcsSecurityGroup'

Outputs:
  EcsSecurityGroup:
    Description: ECS Security Group
    Value: !Ref 'EcsSecurityGroup'
    Export:
      Name: ECS-SG
